[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = UGVpjwWr60Fkf5tFdJG2jHwd9zhDiTsRLYWvZZ74Ul0=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_macbook
PublicKey = 5Y1JXBKTbas/ckUmH1FFsmiz0Ao+N6RxxhxmYnSmG3M=
PresharedKey = u81nKW+EQuIK32M7eKtU3/mqnGtEW52319lfYF2o3Z8=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer_phone
PublicKey = 1+pAq/HhpaJWOX06BTe9g5HdBEBpBsCxHyayXe2jpV8=
PresharedKey = lJyONFD938caH8+00YIqdOGRHekyJQKObUG+qmL1vdU=
AllowedIPs = 10.13.13.3/32

