services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    network_mode: host
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.ollamapi.com
      - WEBHOOK_URL=https://n8n.ollamapi.com
      - N8N_ENCRYPTION_KEY=fb3ccc1219e05721ab11789c6b9400e8
      - GENERIC_TIMEZONE=America/Chicago
      - TZ=America/Chicago
    volumes:
      - /mnt/ssd/n8n/data:/home/node/.n8n
