[Interface]
Address = 10.13.13.2
PrivateKey = MMg0AS39DEuhrPmHMBojIQ1UAm4PW/ONu4PP6Zwm5nc=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = BumnHbEZIA3cOOY0Nkj7n17mm7r+qA/s9/tAa4qRrUY=
PresharedKey = u81nKW+EQuIK32M7eKtU3/mqnGtEW52319lfYF2o3Z8=
Endpoint = ollamapi.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
