[Interface]
Address = 10.13.13.3
PrivateKey = UCOUde/fUgCJatC4iBiGi46iEULdtMQYNFn8HrkXyX8=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = BumnHbEZIA3cOOY0Nkj7n17mm7r+qA/s9/tAa4qRrUY=
PresharedKey = lJyONFD938caH8+00YIqdOGRHekyJQKObUG+qmL1vdU=
Endpoint = ollamapi.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
